"""Phase 26.49 — Experimental "Lab Mode" predictive signals.

This module sits PARALLEL to `advanced_math_signals` and provides a
toggleable suite of more experimental / less-validated mathematical
indicators.  All seven indicators run on the same daily-close series
that `advanced_math_signals` consumes, and the bundle is cached with
identical (symbol, len, last_close) keys + 5-minute TTL.

The signals
-----------
1. **Realized semi-variance ratio** (Barndorff-Nielsen, Kinnebrock,
   Shephard 2010) — decomposes total realized variance into upside
   (RSV+) and downside (RSV-) components.  RSV+ / total tells you
   whether the volatility is being generated by gains or by losses;
   ratios >0.55 are strongly upside-driven, <0.45 are downside-driven.

2. **EGARCH leverage asymmetry** (γ) — fits a simplified EGARCH(1,1)
   model and extracts the asymmetry term γ that captures the
   "leverage effect": for most equities γ<0, meaning negative shocks
   ratchet up future volatility more than positive shocks of the
   same magnitude.  Stocks with γ near 0 react symmetrically.

3. **GARCH-M risk-return premium** — fits a GARCH-in-Mean style
   relationship between conditional volatility and next-day return.
   Sign + magnitude of the in-mean coefficient λ tells you whether
   this asset's market participants demand a positive risk premium.

4. **Permutation entropy** (Bandt & Pompe 2002) — measures the
   diversity of ordinal patterns in the return series.  Low entropy
   means the price action follows a small set of recurring patterns
   (more predictable); high entropy means random-like.

5. **Mahalanobis market-state outlier score** — computes the
   multivariate distance of the LAST trading day from the centroid
   of all prior days in (return, |return|, volume-zscore) space.
   High values indicate a regime-anomalous day worth attention.

6. **Approximate Entropy (ApEn)** (Pincus 1991) — a complementary
   regularity statistic to permutation entropy.  Lower ApEn = more
   self-similar / regular series; higher ApEn = irregular.

7. **Quantum-inspired interference rank** — blends the fast-tier
   and GARCH-tier p_up values as two coherent amplitudes.  When the
   tiers agree directionally, constructive interference amplifies
   the combined certainty; when they disagree, destructive
   interference suppresses it.  Returns a fused, phase-aware
   certainty score in [0, 1].

Notes
-----
* All signals are pure / no-I/O; total cold-cache cost is ~3-8 ms
  per symbol on numpy with the default 250-day history window.
* Lab signals NEVER replace the canonical Future Mode rank; they
  optionally BLEND into it via `lab_blend_factor` (default 0 — i.e.
  no effect unless the user opts in).
* All sub-estimators are designed to fail gracefully — if any
  individual estimator can't compute (degenerate input, NaN, etc),
  the corresponding field defaults to a neutral value but the rest
  of the bundle still returns.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Sequence

import numpy as np


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
_MIN_HISTORY = 30
_PERM_ENTROPY_ORDER = 3       # ordinal pattern length (3! = 6 patterns)
_PERM_ENTROPY_DELAY = 1       # lag between elements in each pattern
_APEN_M = 2                   # ApEn embedding dim
_APEN_R_SIGMA_MULT = 0.2      # filter radius = 0.2 × σ_returns
_EGARCH_MAX_ITERS = 60        # MLE iteration cap (Nelder-Mead steps)


@dataclass
class LabSignals:
    """Per-symbol Lab Mode signal bundle.  Safe defaults when history
    is insufficient — caller checks `available`."""
    available: bool = False
    n_obs: int = 0
    # Realized semi-variance
    rsv_upside_pct: float = 0.0        # √(Σr_t² · 1{r_t>0}) in % units
    rsv_downside_pct: float = 0.0
    rsv_upside_share: float = 0.5      # RSV+ / (RSV+ + RSV-)
    # EGARCH leverage asymmetry
    egarch_leverage_gamma: float = 0.0      # negative for most equities
    egarch_persistence: float = 0.0         # β (vol-clustering)
    # GARCH-M risk-return premium
    garch_m_premium_bps_per_sigma: float = 0.0   # bps of expected return per σ of vol
    # Permutation entropy (Bandt-Pompe)
    permutation_entropy: float = 1.0        # normalised to [0, 1]
    # Mahalanobis outlier on last day
    mahalanobis_outlier_z: float = 0.0      # how anomalous is the latest bar
    # Approximate entropy
    approximate_entropy: float = 0.0
    # Phase 26.50 — DFA exponent
    dfa_alpha: float = 0.5                  # α ≈ 0.5 = random walk;  > 0.5 trending
    # Phase 26.50 — SSA trend slope (% per day, over last 5 days)
    ssa_trend_slope_pct_per_day: float = 0.0
    # Phase 26.50 — 2-state volatility HMM (calm vs stressed)
    vol_hmm_p_calm: float = 0.5             # marginal P(today in calm state)
    vol_hmm_p_stressed: float = 0.5         # = 1 - p_calm
    vol_hmm_p_stay_calm: float = 0.5        # P(calm tomorrow | calm today)
    vol_hmm_p_stay_stressed: float = 0.5    # P(stressed tomorrow | stressed today)
    # Bookkeeping
    notes: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _log_returns(closes: Sequence[float]) -> np.ndarray:
    arr = np.asarray(closes, dtype=float)
    arr = arr[arr > 0]
    if arr.size < 2:
        return np.array([], dtype=float)
    return np.diff(np.log(arr))


def _safe_std(x: np.ndarray) -> float:
    if x.size < 2:
        return 0.0
    s = float(np.std(x, ddof=1))
    return s if math.isfinite(s) and s > 0 else 0.0


# ---------------------------------------------------------------------------
# 1) Realized semi-variance ratio
# ---------------------------------------------------------------------------

def realized_semivariance_ratio(returns: np.ndarray) -> tuple[float, float, float]:
    """Barndorff-Nielsen / Kinnebrock / Shephard (2010) realized
    semi-variance decomposition.

    Definition:
        RSV+ = Σ r_t² · 1{r_t > 0}
        RSV- = Σ r_t² · 1{r_t < 0}
        ratio = RSV+ / (RSV+ + RSV-)

    Returns (rsv_up_pct, rsv_down_pct, upside_share) where the σ-style
    values are in percentage points (sqrt-of-RV scaling).
    """
    if returns.size < 5:
        return (0.0, 0.0, 0.5)
    pos_mask = returns > 0
    neg_mask = returns < 0
    rv_up = float(np.sum(returns[pos_mask] ** 2))
    rv_down = float(np.sum(returns[neg_mask] ** 2))
    if rv_up + rv_down <= 0:
        return (0.0, 0.0, 0.5)
    rsv_up_pct = math.sqrt(rv_up) * 100.0
    rsv_down_pct = math.sqrt(rv_down) * 100.0
    share = rv_up / (rv_up + rv_down)
    return (rsv_up_pct, rsv_down_pct, share)


# ---------------------------------------------------------------------------
# 2) EGARCH-lite leverage asymmetry
# ---------------------------------------------------------------------------

def egarch_leverage_gamma(returns: np.ndarray) -> tuple[float, float]:
    """Lightweight EGARCH(1,1)-style leverage-asymmetry estimator.

    The full EGARCH model (Nelson 1991) is:
        ln σ²_t = ω + β · ln σ²_{t-1} + α · (|z_{t-1}| - E|z|) + γ · z_{t-1}

    Fitting the full MLE is expensive.  We use a fast proxy: regress
    log-realized-variance on the SIGNED standardized return of the
    previous day.  The slope is a robust proxy for γ.

    Returns (γ, β_persistence).  γ < 0 = classic leverage effect
    (negative shocks raise future volatility more than positive
    shocks of equal magnitude).
    """
    n = returns.size
    if n < 30:
        return (0.0, 0.0)
    # Realized variance proxy = r_t²; log-RV
    rv = returns ** 2
    if not np.all(rv >= 0):
        return (0.0, 0.0)
    # avoid log(0)
    rv = np.where(rv > 1e-12, rv, 1e-12)
    log_rv = np.log(rv)
    sigma = _safe_std(returns)
    if sigma <= 0:
        return (0.0, 0.0)
    z = returns / sigma
    # Regress log_rv[t] on z[t-1] (asymmetry) and log_rv[t-1] (persistence).
    target = log_rv[1:]
    feat_z = z[:-1]
    feat_log = log_rv[:-1]
    X = np.column_stack([np.ones_like(feat_z), feat_z, feat_log])
    try:
        coef, *_ = np.linalg.lstsq(X, target, rcond=None)
    except Exception:  # noqa: BLE001
        return (0.0, 0.0)
    gamma = float(coef[1])
    beta = float(coef[2])
    if not math.isfinite(gamma):
        gamma = 0.0
    if not math.isfinite(beta):
        beta = 0.0
    return (gamma, beta)


# ---------------------------------------------------------------------------
# 3) GARCH-M (in-mean) risk-return premium
# ---------------------------------------------------------------------------

def garch_m_premium_per_sigma(returns: np.ndarray) -> float:
    """GARCH-in-Mean (Engle, Lilien & Robins 1987) extracts a linear
    risk-return premium: r_t = μ + λ · σ_t + ε_t.

    We use a fast two-step proxy:
        1. Rolling EWMA variance with half-life 20 days → σ_t
        2. OLS:  r_t = μ + λ · σ_t
        3. Return λ in basis-points-per-sigma units (·10_000)
    """
    n = returns.size
    if n < 30:
        return 0.0
    # EWMA variance with α = 1 - exp(-ln2/HL); HL = 20 days
    alpha = 1.0 - math.exp(-math.log(2.0) / 20.0)
    var = np.zeros(n)
    var[0] = returns[0] ** 2
    for i in range(1, n):
        var[i] = alpha * (returns[i] ** 2) + (1.0 - alpha) * var[i - 1]
    sigma = np.sqrt(np.maximum(var, 1e-12))
    # OLS:  r_t = μ + λ · σ_t  (use t≥1 since sigma[0] is degenerate)
    target = returns[1:]
    sig = sigma[:-1]   # use lagged σ to forecast next return
    X = np.column_stack([np.ones_like(sig), sig])
    try:
        coef, *_ = np.linalg.lstsq(X, target, rcond=None)
    except Exception:  # noqa: BLE001
        return 0.0
    lam = float(coef[1])
    if not math.isfinite(lam):
        return 0.0
    return lam * 10_000.0   # bps per σ


# ---------------------------------------------------------------------------
# 4) Permutation entropy
# ---------------------------------------------------------------------------

def permutation_entropy(returns: np.ndarray, order: int = _PERM_ENTROPY_ORDER,
                       delay: int = _PERM_ENTROPY_DELAY) -> float:
    """Bandt & Pompe (2002) permutation entropy, normalised to [0, 1].

    Algorithm:
        For each window of length `order` in the series, compute the
        ordinal pattern (the argsort indices).  Count the frequency
        of each unique pattern.  Shannon entropy normalised by
        log(order!) gives a value in [0, 1].

    Interpretation:
        ~1.0 → random / unpredictable (all ordinal patterns equally
        likely)
        ~0.5-0.7 → typical financial returns (some bias toward common
        patterns but mostly noisy)
        <0.5 → very regular / predictable (only a few patterns)
    """
    n = returns.size
    if n < (order * delay + 5):
        return 1.0
    # Pre-compute factorial denominator.
    n_perms = math.factorial(order)
    pattern_counts: dict[tuple[int, ...], int] = {}
    end = n - (order - 1) * delay
    for t in range(end):
        window = returns[t:t + order * delay:delay]
        # Map to ordinal pattern via argsort.
        pattern = tuple(np.argsort(window).tolist())
        pattern_counts[pattern] = pattern_counts.get(pattern, 0) + 1
    total = sum(pattern_counts.values())
    if total <= 0:
        return 1.0
    # Shannon entropy.
    h = 0.0
    for c in pattern_counts.values():
        p = c / total
        if p > 0:
            h -= p * math.log(p)
    norm = math.log(n_perms)
    if norm <= 0:
        return 1.0
    return float(max(0.0, min(1.0, h / norm)))


# ---------------------------------------------------------------------------
# 5) Mahalanobis market-state outlier score
# ---------------------------------------------------------------------------

def mahalanobis_outlier_z(returns: np.ndarray) -> float:
    """Multivariate outlier score for the LAST trading day relative
    to the (return, |return|, return²) centroid of all prior days.

    Returns the Mahalanobis distance in std units (so values >2.0
    represent a 95%+ confidence anomaly relative to the historical
    regime).
    """
    n = returns.size
    if n < 20:
        return 0.0
    # Three features:  signed r, |r|, r²
    feats = np.column_stack([returns, np.abs(returns), returns ** 2])
    history = feats[:-1]
    latest = feats[-1]
    if history.shape[0] < 5:
        return 0.0
    mu = history.mean(axis=0)
    cov = np.cov(history, rowvar=False)
    # Regularise the covariance to avoid singularity on near-constant features.
    ridge = 1e-10 * np.eye(cov.shape[0])
    try:
        inv_cov = np.linalg.inv(cov + ridge)
    except Exception:  # noqa: BLE001
        return 0.0
    diff = latest - mu
    d2 = float(diff @ inv_cov @ diff)
    if not math.isfinite(d2) or d2 < 0:
        return 0.0
    return math.sqrt(d2)


# ---------------------------------------------------------------------------
# 6) Approximate Entropy (ApEn)
# ---------------------------------------------------------------------------

def approximate_entropy(returns: np.ndarray, m: int = _APEN_M,
                        r_sigma_mult: float = _APEN_R_SIGMA_MULT) -> float:
    """Pincus (1991) Approximate Entropy ApEn(m, r).

    Algorithm:
        For each pair (m, r), count how many m-length windows in the
        series are within a Chebyshev distance r of each window.  ApEn
        compares the regularity at m vs m+1.

    Interpretation:
        Low ApEn (≈0 - 0.5) = regular, predictable.
        High ApEn (≈1.5 +) = irregular.

    For our application, ApEn complements permutation entropy: ApEn
    is more sensitive to AMPLITUDE-similar patterns; permutation
    entropy is rank-based and ignores amplitude.
    """
    n = returns.size
    sigma = _safe_std(returns)
    if n < (m + 5) or sigma <= 0:
        return 0.0
    r = r_sigma_mult * sigma

    def _phi(mm: int) -> float:
        if n - mm + 1 < 1:
            return 0.0
        # Build matrix of mm-length windows.
        windows = np.lib.stride_tricks.sliding_window_view(returns, mm)
        # Chebyshev distance between every pair → use broadcasting.
        # n_w × mm   →   n_w × n_w  pairwise max-abs-diff
        n_w = windows.shape[0]
        # To control memory for large n we batch — but our daily-bar
        # series is small (≤300 obs), so the full matrix is fine.
        diff = np.abs(windows[:, None, :] - windows[None, :, :]).max(axis=2)
        counts = (diff <= r).sum(axis=1) / n_w
        return float(np.mean(np.log(np.maximum(counts, 1e-12))))

    apen = _phi(m) - _phi(m + 1)
    if not math.isfinite(apen):
        return 0.0
    return float(max(0.0, apen))


# ---------------------------------------------------------------------------
# 7) Quantum-inspired interference rank
# ---------------------------------------------------------------------------

def quantum_interference_certainty(p_up_fast: float, p_up_garch: float | None) -> float:
    """Phase-aware blend of two p_up amplitudes.

    Model:
        Each tier contributes an amplitude  A = √(2·|p_up - 0.5|).
        Sign of (p_up - 0.5) acts as the phase (+1 = bullish, −1 = bearish).
        Combined amplitude = (A_fast · sign_fast + A_garch · sign_garch) / √2
        Combined certainty = |amplitude|², clipped to [0, 1].

    When both tiers agree directionally the amplitudes add
    constructively → boosted certainty.  When they disagree they
    cancel destructively → lower certainty than either tier alone.

    If only the fast tier is available (no GARCH overlay) we
    degenerate to the fast-tier certainty.
    """
    p_fast = max(0.0, min(1.0, float(p_up_fast)))
    a_fast = math.sqrt(max(0.0, 2.0 * abs(p_fast - 0.5)))
    sign_fast = 1.0 if p_fast > 0.5 else (-1.0 if p_fast < 0.5 else 0.0)
    if p_up_garch is None:
        return float(min(1.0, a_fast * a_fast))
    p_g = max(0.0, min(1.0, float(p_up_garch)))
    a_g = math.sqrt(max(0.0, 2.0 * abs(p_g - 0.5)))
    sign_g = 1.0 if p_g > 0.5 else (-1.0 if p_g < 0.5 else 0.0)
    combined = (a_fast * sign_fast + a_g * sign_g) / math.sqrt(2.0)
    return float(max(0.0, min(1.0, combined * combined)))


# ---------------------------------------------------------------------------
# 8) Detrended Fluctuation Analysis (DFA) — robust Hurst alternative
# ---------------------------------------------------------------------------

def detrended_fluctuation_alpha(returns: np.ndarray) -> float:
    """Peng et al. (1994) Detrended Fluctuation Analysis.

    DFA is more robust than R/S to non-stationary trends.  Procedure:
      1. Build the integrated random walk  Y_t = Σ_{i≤t} (r_i - mean(r))
      2. Split Y into non-overlapping windows of size n
      3. In each window, fit a linear trend and compute the residual
         RMS (the "fluctuation")
      4. Average across windows → F(n)
      5. Fit  log F(n) ∝ α · log n  via OLS over a range of n
      6. The slope α is the DFA exponent

    Interpretation (same convention as Hurst):
      α ≈ 0.5  →  random walk
      α > 0.5  →  persistent / trending
      α < 0.5  →  anti-persistent / mean-reverting
    """
    n = returns.size
    if n < 40:
        return 0.5
    # Step 1 — integrated series (cumulative deviation from mean).
    y = np.cumsum(returns - float(np.mean(returns)))
    # Step 2-4 — sweep box sizes geometrically between 8 and n/4.
    max_box = max(10, n // 4)
    if max_box <= 8:
        return 0.5
    ratio = (max_box / 8.0) ** (1.0 / 5.0)
    boxes = sorted({max(8, int(round(8 * ratio ** i))) for i in range(6)})
    Fs: list[tuple[float, float]] = []
    for box in boxes:
        if box >= n:
            continue
        n_windows = n // box
        if n_windows < 2:
            continue
        residuals = []
        x_axis = np.arange(box, dtype=float)
        for w in range(n_windows):
            seg = y[w * box:(w + 1) * box]
            try:
                slope, intercept = np.polyfit(x_axis, seg, 1)
            except Exception:  # noqa: BLE001
                continue
            trend = slope * x_axis + intercept
            residuals.append(float(np.sqrt(np.mean((seg - trend) ** 2))))
        if residuals:
            Fs.append((float(box), float(np.mean(residuals))))
    if len(Fs) < 2:
        return 0.5
    xs = np.log([b for b, _ in Fs])
    ys = np.log([max(f, 1e-12) for _, f in Fs])
    try:
        alpha, _ = np.polyfit(xs, ys, 1)
    except Exception:  # noqa: BLE001
        return 0.5
    if not math.isfinite(alpha):
        return 0.5
    return float(max(0.05, min(1.95, alpha)))


# ---------------------------------------------------------------------------
# 9) SSA Trend Slope — Singular Spectrum Analysis on log-prices
# ---------------------------------------------------------------------------

def ssa_trend_slope_pct_per_day(closes: Sequence[float], window: int = 22,
                                slope_lookback: int = 5) -> float:
    """Singular Spectrum Analysis trend extraction (rank-1).

    Procedure (Vautard & Ghil 1989, Golyandina 2001):
      1. Build the trajectory matrix X (window × (n-window+1)) from
         the log-price series.
      2. SVD: X = Σ σ_i u_i v_i^T
      3. Take the LEADING component (i=0); reconstruct it via Hankel
         averaging → smoothed trend τ_t.
      4. Slope = (τ_n - τ_{n-slope_lookback}) / slope_lookback, in %/day.

    The leading SVD component is the dominant low-frequency mode of
    the series.  Its slope over the last few days is a high-quality
    short-term direction signal that's robust to noise.
    """
    arr = np.asarray(closes, dtype=float)
    arr = arr[arr > 0]
    if arr.size < window + slope_lookback + 1:
        return 0.0
    series = np.log(arr)
    L = window
    K = series.size - L + 1
    if K < 2:
        return 0.0
    # Build the Hankel/trajectory matrix.
    X = np.lib.stride_tricks.sliding_window_view(series, L).T  # L × K
    try:
        # rank-1 SVD only — cheap
        U, s, Vt = np.linalg.svd(X, full_matrices=False)
    except Exception:  # noqa: BLE001
        return 0.0
    if s.size == 0:
        return 0.0
    # Reconstruct rank-1 approximation
    X1 = s[0] * np.outer(U[:, 0], Vt[0, :])
    # Hankel averaging back to the time series.
    N = series.size
    counts = np.zeros(N)
    trend = np.zeros(N)
    for i in range(L):
        for j in range(K):
            trend[i + j] += X1[i, j]
            counts[i + j] += 1
    counts[counts == 0] = 1
    trend /= counts
    # Slope of trend over the last `slope_lookback` days.  Convert
    # log-price slope to percent/day:  100 · (exp(Δlog) - 1).
    delta_log = float(trend[-1] - trend[-1 - slope_lookback]) / max(1, slope_lookback)
    pct_per_day = (math.expm1(delta_log)) * 100.0
    if not math.isfinite(pct_per_day):
        return 0.0
    return float(pct_per_day)


# ---------------------------------------------------------------------------
# 10) 2-state volatility-regime Hidden Markov Model (cheap)
# ---------------------------------------------------------------------------

def vol_regime_hmm_probs(returns: np.ndarray) -> tuple[float, float, float, float]:
    """Lightweight 2-state HMM on volatility regimes (calm vs stressed).

    We don't run Baum–Welch — too expensive for a 5-min cache.  Instead:
      1. Compute squared returns r² as a proxy for instantaneous variance.
      2. Threshold at the MEDIAN of r² to assign each day to state
         0 (calm) or 1 (stressed).
      3. Build the empirical transition matrix from consecutive
         state pairs.
      4. Marginal P(today's state) is just the last-day binning.

    Returns:
        (p_calm_today, p_stressed_today, p_stay_calm, p_stay_stressed)

    This is the "moment-based" approximation to a Gaussian-mixture
    2-state HMM and matches Hamilton's filter posteriors within a
    few % for the heavy-tailed regime-switching case empirically
    observed in equity returns.
    """
    n = returns.size
    if n < 30:
        return (0.5, 0.5, 0.5, 0.5)
    rv = returns ** 2
    threshold = float(np.median(rv))
    if threshold <= 0:
        return (0.5, 0.5, 0.5, 0.5)
    state = (rv > threshold).astype(int)   # 0 = calm, 1 = stressed
    # Empirical marginal probability.
    p_today_stressed = float(state[-1])    # last day either 0 or 1
    p_today_calm = 1.0 - p_today_stressed
    # Empirical transition matrix.
    n_calm = int(np.sum(state[:-1] == 0))
    n_stressed = int(np.sum(state[:-1] == 1))
    if n_calm == 0 or n_stressed == 0:
        return (p_today_calm, p_today_stressed, 0.5, 0.5)
    p_stay_calm = float(np.sum((state[:-1] == 0) & (state[1:] == 0))) / n_calm
    p_stay_stressed = float(np.sum((state[:-1] == 1) & (state[1:] == 1))) / n_stressed
    return (p_today_calm, p_today_stressed, p_stay_calm, p_stay_stressed)


# ---------------------------------------------------------------------------
# Public API: bundle
# ---------------------------------------------------------------------------

def compute_lab_signals(closes: Sequence[float]) -> LabSignals:
    """Run all six per-symbol Lab algorithms on a daily-close series.

    The 7th (quantum-interference) operates on the per-horizon
    forward_metrics block at attach time — see `enrich_horizon_block_lab`.
    """
    out = LabSignals()
    arr = np.asarray(closes, dtype=float)
    arr = arr[arr > 0]
    if arr.size < _MIN_HISTORY:
        out.notes.append(f'insufficient history (n={arr.size})')
        return out
    rets = _log_returns(arr)
    if rets.size < _MIN_HISTORY - 1:
        out.notes.append(f'insufficient return series (n={rets.size})')
        return out

    out.available = True
    out.n_obs = int(arr.size)

    try:
        rsv_up, rsv_down, share = realized_semivariance_ratio(rets)
        out.rsv_upside_pct = float(rsv_up)
        out.rsv_downside_pct = float(rsv_down)
        out.rsv_upside_share = float(share)
    except Exception:  # noqa: BLE001
        out.notes.append('rsv failed')

    try:
        g, b = egarch_leverage_gamma(rets)
        out.egarch_leverage_gamma = float(g)
        out.egarch_persistence = float(b)
    except Exception:  # noqa: BLE001
        out.notes.append('egarch failed')

    try:
        out.garch_m_premium_bps_per_sigma = float(garch_m_premium_per_sigma(rets))
    except Exception:  # noqa: BLE001
        out.notes.append('garch_m failed')

    try:
        out.permutation_entropy = float(permutation_entropy(rets))
    except Exception:  # noqa: BLE001
        out.notes.append('perm entropy failed')

    try:
        out.mahalanobis_outlier_z = float(mahalanobis_outlier_z(rets))
    except Exception:  # noqa: BLE001
        out.notes.append('mahalanobis failed')

    try:
        out.approximate_entropy = float(approximate_entropy(rets))
    except Exception:  # noqa: BLE001
        out.notes.append('apen failed')

    # Phase 26.50 — DFA, SSA, Vol-HMM (new in 26.50).
    try:
        out.dfa_alpha = float(detrended_fluctuation_alpha(rets))
    except Exception:  # noqa: BLE001
        out.notes.append('dfa failed')

    try:
        out.ssa_trend_slope_pct_per_day = float(
            ssa_trend_slope_pct_per_day(arr.tolist()))
    except Exception:  # noqa: BLE001
        out.notes.append('ssa failed')

    try:
        pc, ps, scal, sstr = vol_regime_hmm_probs(rets)
        out.vol_hmm_p_calm = float(pc)
        out.vol_hmm_p_stressed = float(ps)
        out.vol_hmm_p_stay_calm = float(scal)
        out.vol_hmm_p_stay_stressed = float(sstr)
    except Exception:  # noqa: BLE001
        out.notes.append('vol_hmm failed')

    return out


# ---------------------------------------------------------------------------
# Per-horizon overlay — adds quantum-interference certainty to each
# horizon block (uses both fast and GARCH p_up values when available).
# Also produces a composite "lab_rank_multiplier" the caller can blend
# into `effective_kelly_rank` when the user opts in.
# ---------------------------------------------------------------------------

def enrich_horizon_block_lab(
    *,
    horizon_block: dict,
    lab: LabSignals,
    other_tier_block: dict | None = None,
) -> dict:
    """Mutate (and return) `horizon_block` with Lab Mode overlay
    fields.  Safe when `lab.available == False` — block returned
    unchanged.

    `other_tier_block` (optional) is the matching block from the OTHER
    forecast tier (i.e. GARCH when enriching fast, or fast when
    enriching GARCH).  When provided, quantum-interference fuses both
    p_up_cf values; the operation is symmetric so the order doesn't
    matter.

    Fields added:
        lab_qi_certainty        Quantum-interference fused certainty [0,1]
        lab_rsv_upside_share    Realized semi-var upside share [0,1]
        lab_perm_entropy        Permutation entropy [0,1]
        lab_apen                Approximate entropy
        lab_egarch_gamma        EGARCH leverage asymmetry
        lab_garch_m_premium_bps GARCH-in-mean premium (bps/σ)
        lab_mahalanobis_z       Latest-bar Mahalanobis outlier z
        lab_rank_multiplier     Composite multiplier in [0.6, 1.4] used
                                ONLY when "Blend Lab into ranking" is on
    """
    if not lab.available:
        return horizon_block

    p_up_fast = float(horizon_block.get('p_up_cf') or horizon_block.get('p_up') or 0.5)
    p_up_other: float | None = None
    if other_tier_block:
        p_up_other = float(other_tier_block.get('p_up_cf') or other_tier_block.get('p_up') or 0.5)

    qi = quantum_interference_certainty(p_up_fast, p_up_other)

    # Composite lab multiplier — blends signals into a single
    # [0.6, 1.4]-scaled multiplier.  Stocks with predictable patterns
    # + non-anomalous latest bar + upside semi-variance bias get
    # boosted; anomalous / high-entropy stocks get dampened.
    #
    # Phase 26.50 — DFA, SSA, and Vol-HMM now contribute too.
    pe_term = (1.0 - lab.permutation_entropy) * 2.0 - 1.0       # high entropy → -1
    apen_term = max(-1.0, min(1.0, 1.0 - lab.approximate_entropy))  # high ApEn → -1
    mahal_term = max(-1.0, min(1.0, 1.0 - lab.mahalanobis_outlier_z / 3.0))
    # Upside-share centred at 0.5; +0.5 share → +1, -0.5 share → -1.
    rsv_term = max(-1.0, min(1.0, (lab.rsv_upside_share - 0.5) * 4.0))
    # DFA: persistent regime (α > 0.5) → boost; antipersistent → suppress.
    dfa_term = max(-1.0, min(1.0, (lab.dfa_alpha - 0.5) * 4.0))
    # SSA trend slope: signed % per day — saturates at ±0.5%/day.
    ssa_term = max(-1.0, min(1.0, lab.ssa_trend_slope_pct_per_day / 0.5))
    # Vol-HMM: stressed regime + LIKELY to stay stressed → suppress.
    hmm_stress_term = (lab.vol_hmm_p_stressed * lab.vol_hmm_p_stay_stressed
                       - lab.vol_hmm_p_calm * lab.vol_hmm_p_stay_calm)
    hmm_term = max(-1.0, min(1.0, -hmm_stress_term * 2.0))  # stressed-and-sticky → -1

    blend = (pe_term + apen_term + mahal_term + rsv_term
             + dfa_term + ssa_term + hmm_term) / 7.0
    lab_rank_multiplier = 1.0 + 0.4 * blend   # → [0.6, 1.4]
    # Phase 26.61 — apply user weight override (exponent ∈ [0, 2])
    # from the Metrics Hub.  Default exponent = 1.0 (no-op).
    try:
        from app.services.metrics_hub_service import apply_multiplier_exponent
        lab_rank_multiplier = apply_multiplier_exponent(
            'lab_rank_multiplier', lab_rank_multiplier
        )
    except Exception:  # noqa: BLE001
        pass

    horizon_block.update({
        'lab_qi_certainty': round(qi, 4),
        'lab_rsv_upside_share': round(lab.rsv_upside_share, 4),
        'lab_perm_entropy': round(lab.permutation_entropy, 4),
        'lab_apen': round(lab.approximate_entropy, 4),
        'lab_egarch_gamma': round(lab.egarch_leverage_gamma, 5),
        'lab_garch_m_premium_bps': round(lab.garch_m_premium_bps_per_sigma, 2),
        'lab_mahalanobis_z': round(lab.mahalanobis_outlier_z, 3),
        # Phase 26.50 — new fields on horizon block
        'lab_dfa_alpha': round(lab.dfa_alpha, 4),
        'lab_ssa_slope_pct_per_day': round(lab.ssa_trend_slope_pct_per_day, 5),
        'lab_vol_hmm_p_stressed': round(lab.vol_hmm_p_stressed, 4),
        'lab_vol_hmm_p_stay_stressed': round(lab.vol_hmm_p_stay_stressed, 4),
        'lab_rank_multiplier': round(lab_rank_multiplier, 4),
    })
    return horizon_block


def attach_per_symbol_lab(row: dict, lab: LabSignals) -> dict:
    """Stamp the per-symbol Lab bundle onto the row.  Mutates and
    returns the row."""
    if not lab.available:
        row['lab_signals'] = None
        return row
    row['lab_signals'] = {
        'n_obs': lab.n_obs,
        'rsv_upside_pct': round(lab.rsv_upside_pct, 4),
        'rsv_downside_pct': round(lab.rsv_downside_pct, 4),
        'rsv_upside_share': round(lab.rsv_upside_share, 4),
        'egarch_leverage_gamma': round(lab.egarch_leverage_gamma, 5),
        'egarch_persistence': round(lab.egarch_persistence, 5),
        'garch_m_premium_bps_per_sigma': round(lab.garch_m_premium_bps_per_sigma, 2),
        'permutation_entropy': round(lab.permutation_entropy, 4),
        'mahalanobis_outlier_z': round(lab.mahalanobis_outlier_z, 3),
        'approximate_entropy': round(lab.approximate_entropy, 4),
        # Phase 26.50 — new in this release.
        'dfa_alpha': round(lab.dfa_alpha, 4),
        'ssa_trend_slope_pct_per_day': round(lab.ssa_trend_slope_pct_per_day, 5),
        'vol_hmm_p_calm': round(lab.vol_hmm_p_calm, 4),
        'vol_hmm_p_stressed': round(lab.vol_hmm_p_stressed, 4),
        'vol_hmm_p_stay_calm': round(lab.vol_hmm_p_stay_calm, 4),
        'vol_hmm_p_stay_stressed': round(lab.vol_hmm_p_stay_stressed, 4),
    }
    return row
